### ISSUE TITLE
Eat

### ISSUE THREAD

**Issue by spookycutie08** [bwhitworth/tamagotchi#4]
## USER STORY
As a user, I should see use the EAT quad to feed my Tamagotchi pet.

## AC
WHEN the page loads, the EAT quad should be in the upper left quad
THEN it should display the quad name (EAT), fullness score (default to 100)
AND it should have two buttons - healthy food (adds 10 to score) and junk food (subtracts 3)
AND the fullness score should update any time a button is pushed
AND the fullness score cannot go above 100 or below 0

## DEV NOTES
- [x] inside `src/styles`, create a new file called `eat.scss` (leave empty for ticket #5)

- [x] in `src/javacripts/helpers` folder, create a new file called `data.js`

- [x] in `data.js`, declare a new object called `pet` with key `full` at value 100

- [x] create a reusable function called `scorePrinter` that takes in arguments of `quadDiv` and `scoreToPrint`, then works like the `printToDom` function. It should print a value as an `<h3>` tag inside of a particular quad (example: `scorePrinter(eat, full)` should print the fullness score inside the eat quad)

- [x] create a new function called `feedHealthyFood` that adds 10 to the value of `pet.full` (and makes sure it cannot go above 100) then reprints the updated score with `scorePrinter`

- [x] create a similar reusable function called `feedJunkFood` that that subtracts 3 from the value of `pet.full` (and makes sure it cannot go below 0) then reprints the updated score with `scorePrinter`

- [x] export default `full, feedHealthyFood, feedJunkFood, and scorePrinter`

- [x] in `src/javacripts` folder, create a new folder called `components`

- [x] inside `components`, create a file called `eat.js`. Inside that file:

- [x] import  `data.js` and `utils.js`

- [x] create a new function called `eatQuadPrinter` that uses `printToDom` to:

1. print an h2 header for the title of the quad (EAT)

1. print a child `div` inside of the `quad` div, which will receive the fullness score (when we use `scorePrinter`).  Give it an `id='eat-score-container`.

1. print two buttons (healthy food and junk food) inside the parent `div id='eat'`

1. give each button an `id` (healthy-food-btn and junk-food-btn)

1. use jquery code to assign event listeners to each button on click (healthy food button runs `feedHealthyFood` function and junk food button runs `feedJunkFood` function

- [x] export `eatQuadPrinter`

- [x] import `eatQuadPrinter` to `main.js`, build an `init` function and call it within that, then init for page load.

**Comment by bwhitworth** [comment]
Works, but might refactor code to be more reusable.  Will not close ticket yet.

**Comment by spookycutie08** [comment]
Quad works. Will be refactoring some code and applying Sass style in other tickets.
