### ISSUE TITLE
Play

### ISSUE THREAD

**Issue by spookycutie08** [bwhitworth/tamagotchi#9]
## USER STORY
As a user, I should see use the PLAY quad for my Tamagotchi pet.

## AC
WHEN the page loads, the PLAY quad should be in the upper right quad
THEN it should display the quad name (PLAY), and playful score (default to 50)
AND it should have two buttons - super fun (adds 50 to score) and sorta fun (adds 2)
AND the playful score should update any time a button is pushed
AND the play score cannot go above 100

## DEV NOTES
- [x] inside `src/styles`, create a new file called `play.scss` (leave empty for ticket #5)

- [x] in `data.js`, declare a new value for the `pet` object called `fun` and assign value 50.

- [x] create a new function called `superFunActivity` that adds 50 to the value of `pet.fun` (and makes sure it cannot go above 100) then reprints the updated score with `scorePrinter`

- [x] create a similar function called `sortaFunActivity` that that adds 2 the value of `pet.fun` (and makes sure it cannot go above 100) then reprints the updated score with `scorePrinter`

- [x] export default `superFunActivity, and sortaFunActivity`

- [x] inside `components`, create a file called `play.js`. Inside that file:

- [x] import  `data.js` and `utils.js`

- [x] create a new function called `playQuadPrinter` that uses `printToDom` to:

1. print an h2 header for the title of the quad (PLAY)

1. print a child `div` inside of the `quad` div, which will receive the fun score (when we use `scorePrinter`).  Give it an `id='play-score-container`.

1. print two buttons (super fun and sorta fun) inside the parent `div id='play'`

1. give each button an `id` (super-fun-btn and sorta-fun-btn)

1. use jquery code to assign event listeners to each button on click (super fun button runs `superFunActivity` function and sorta fun button runs `sortaFunActivity` function

- [x] export `playQuadPrinter`

- [x] import `playQuadPrinter` to `main.js` and call it within the `init` function body

**Comment by bwhitworth** [comment]
Works for now, but may need to refactor some code to be more reusable.  Also waiting to apply SASS. Will not close ticket yet.

**Comment by spookycutie08** [comment]
Quad works. Will be refactoring some code and applying Sass style in other tickets.
